### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by rewold** [HookedBehemoth/tmc_strings#1]
![image](https://user-images.githubusercontent.com/38116192/103426439-a5ad3100-4bca-11eb-89d2-938987d0d697.png)

**Comment by HookedBehemoth** [comment]
Did you clone/download the entire repository?
The folder fmt is included.

**Comment by rewold** [comment]
I solved this problem. I don't know about software but I learned about "make" and "gcc" on Ubuntu. I made extract strings. Thank you for reply.
